### ISSUE TITLE
Research styling options

### ISSUE THREAD

**Issue by kevinfalting** [bldg14/eventual#20]
How should we go about adding styles to the app? There are a number of candidates to choose from, in no particular order:
- https://getbootstrap.com
- https://tailwindcss.com
- http://getskeleton.com
- https://mui.com

I'm certain there are others. This issue is for research, no PR needed. Detail findings and a recommendation as comments on this issue.

**Comment by eduenez33** [comment]
I am most familiar with bootstrap. It could be too basic style-wise, although it really has leveled up quite a bit with its latest release.

All the different options have great documentation

**Comment by eduenez33** [comment]
## [React Bootstrap](https://react-bootstrap.github.io/)
- Each component has been built from scratch as a true React component, without unneeded dependencies like jQuery.
- Great documentation
- Prior knowledge of the framework

**Comment by eduenez33** [comment]
Decided to go with the react-bootstrap framework. Closing this issue with #22 
Any further research or comments can be posted here
