### ISSUE TITLE
Create the title component

### ISSUE THREAD

**Issue by kevinfalting** [bldg14/eventual#6]
The title component should be a simple function component that takes a title string and returns the title wrapped in an H1 tag.

```tsx
const Title = ({title}: {title: string}) => <h1>{title}</h1>
```

And then place it in the App.tsx file so that it displays the title.

**Comment by kevinfalting** [comment]
Doesn't have to be exactly like this, feel free to explore options.

**Comment by eduenez33** [comment]
@kevinfalting Let me know what you think. https://github.com/bldg14/eventual/commit/0891f6017c330f7fae16c2a38b9142bc2b1a7a69
https://github.com/bldg14/eventual/commit/aa68d5b5bb2b83268075f1f7cd6b73f1d1005df7
